# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'joybox'

Motion::Project::App.setup do |app|
  app.name = 'Total Tacos'
  app.interface_orientations = [:landscape_left]
  app.device_family = [:ipad]
  app.icons = ['icon.png', 'icon@2x.png']
  app.prerendered_icon = true
  app.deployment_target = "6.0"
  app.codesign_certificate = "iPhone Distribution: Iconoclast Labs LLC"
end
